module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",        
      {
        "muthur6k": {
          "primary": "#D6FFC5",
          "secondary": "#FDFEC4",
          "accent": "#D2D53F",
          "neutral": "#5D7753",
          "base-100": "#231F20",
          'base-300': '#293723', // Use for table hover
          "info": "#D3FEC2",
          "success": "#8BDD6F",
          "warning": "#D2D53F",
          "error": "#AC4F4F",
        },
        "atompunkmoderna": {
          "primary": "#bc0954",
          "secondary": "#ecf29b",
          "accent": "#4679af",
          "neutral": "#23283E",
          "base-100": "#323135",
          "info": "#73A6F7",
          "success": "#249E7D",
          "warning": "#F8C53A",
          "error": "#FB6D60",
        },
      }
    ],
  },
  plugins: [require("daisyui")],
};
