module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    'node_modules/daisyui/dist/**/*.js',
    'node_modules/react-daisyui/dist/**/*.js'
],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",        
      {
        "muthur6k": {
          "primary": "#D6FFC5",
          "secondary": "#FDFEC4",
          "accent": "#D2D53F",
          "neutral": "#5D7753",
          "base-100": "#231F20",
          'base-300': '#293723', // Use for table hover
          "info": "#D3FEC2",
          "success": "#8BDD6F",
          "warning": "#D2D53F",
          "error": "#AC4F4F",
        },
        "atompunkmoderna": {
          "primary": "#bc0954",
          "secondary": "#ecf29b",
          "accent": "#4679af",
          "neutral": "#23283E",
          "base-100": "#323135",
          "info": "#73A6F7",
          "success": "#249E7D",
          "warning": "#F8C53A",
          "error": "#FB6D60",
        },
        "duskers": {
          primary: "#c5e838",
          secondary: "#2653a6",
          accent: "#ecf29b",
          neutral: "#2c4745",
          "neutral-content": "#37edb3",
          "base-content": "#37edb3",
          "base-100": "#09090b",
          "base-200": "#191f1d",
          "base-300": "#1c3328",
          fontFamily: "ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--tab-radius": "0",
        },
      }
    ],
  },
  plugins: [require("daisyui"), require('daisyui-tailwind-scrollbar')],
};
